### ISSUE TITLE
Versioning division properties

### ISSUE THREAD

**Issue by paultag** [opencivicdata/ocd-division-ids#112]
So, we need to revise how we do `census_geoid` a bit.

This works, and _did_ work when we had a single geometry to map to -- the problem is, with the new vintages of the census data, the IDs are all jumbled up a bit.

I'd like to change `census_geoid` to `census_geoid_12`, and create a new field, `census_geoid_14` for the new set.

Thoughts from others? I'll start working up a PR, but I'll put this here in the meantime.

**Comment by paultag** [comment]
I'm also guessing this is primarally a US issue, but I imagine this bug will translate wherever we have multiple versions of shapefiles that we relate to

**Comment by paultag** [comment]
Partial fix in place; needs work for place, & county

**Comment by paultag** [comment]
and cd-*

**Comment by jpmckinney** [comment]
So, I guess we're talking about versioned properties? We currently only have a facility for versioning IDs with validFrom, validThrough. In Canada, I haven't yet encountered a use case where I needed to version a property; our Census tries hard to maintain IDs over time, and to not reuse an ID until several decades have passed. But I haven't really plumbed historical use cases.

Also, I'd prefer to use a full YYYY year suffix instead of YY. In Canada, I use two-letter language code suffixes for translations.

**Comment by jpmckinney** [comment]
Closing as the original issue was fixed, and we don't need to set a policy on how to name the columns for custom properties of different vintages.
